name: Java CI with Maven

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
         host: ${{ secrets.SONARQUBE_HOST }}
         login: ${{ secrets.SONARQUBE_TOKEN }}
         projectKey: master-sir-2024

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build and Test
        run: ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install

      - name: SonarQube Analysis
        run: ./mvnw sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.TokenSonar }} # You might need to provide the token again here

      - name: Approve Deployment
        run: echo "Deploying into Server"
        if: github.event_name == 'pull_request'

      - name: Send Message on Aborted/Failure/Success
        run: echo "Sending message to agent"
        if: always()





